--------------------------------------------------------
--  File created - понедельник-марта-21-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."CITY" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEATHER
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."WEATHER" 
   (	"CREATED_AT" DATE, 
	"WIND_SPEED" NUMBER, 
	"WIND_DIRECTION" NUMBER, 
	"WIND_GUST" NUMBER, 
	"CITY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ADMIN.CITY
SET DEFINE OFF;
Insert into C##ADMIN.CITY (ID,NAME) values ('1','Izhevsk');
Insert into C##ADMIN.CITY (ID,NAME) values ('2','Samara');
Insert into C##ADMIN.CITY (ID,NAME) values ('3','Volgograd');
Insert into C##ADMIN.CITY (ID,NAME) values ('4','Saint-Petersburg');
REM INSERTING into C##ADMIN.WEATHER
SET DEFINE OFF;
Insert into C##ADMIN.WEATHER (CREATED_AT,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('20.03.22','DD.MM.RR'),'11,6','291,6','26,6','1');
Insert into C##ADMIN.WEATHER (CREATED_AT,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('17.03.22','DD.MM.RR'),'8,9','273,2','15,4','1');
Insert into C##ADMIN.WEATHER (CREATED_AT,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('21.03.22','DD.MM.RR'),'13,4','338,6','29,1','1');
Insert into C##ADMIN.WEATHER (CREATED_AT,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.03.22','DD.MM.RR'),'8,7','263,7','19,9','1');
Insert into C##ADMIN.WEATHER (CREATED_AT,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.03.22','DD.MM.RR'),'5,4','207,1','11,4','1');
--------------------------------------------------------
--  DDL for Index CITY_NAME_UINDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_NAME_UINDEX" ON "C##ADMIN"."CITY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_PK" ON "C##ADMIN"."CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WEATHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."WEATHER_PK" ON "C##ADMIN"."WEATHER" ("CREATED_AT", "CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_PK" ON "C##ADMIN"."CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_NAME_UINDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_NAME_UINDEX" ON "C##ADMIN"."CITY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WEATHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."WEATHER_PK" ON "C##ADMIN"."WEATHER" ("CREATED_AT", "CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ADMIN"."CITY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WEATHER
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."WEATHER" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."WEATHER" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."WEATHER" ADD CONSTRAINT "WEATHER_PK" PRIMARY KEY ("CREATED_AT", "CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEATHER
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."WEATHER" ADD CONSTRAINT "CITY_ID" FOREIGN KEY ("CITY_ID")
	  REFERENCES "C##ADMIN"."CITY" ("ID") ENABLE;
