--------------------------------------------------------
--  File created - воскресенье-апреля-17-2022   
--------------------------------------------------------
DROP SEQUENCE "C##ADMIN"."ISEQ$$_76267";
DROP SEQUENCE "C##ADMIN"."ISEQ$$_76270";
DROP TABLE "C##ADMIN"."CITY";
DROP TABLE "C##ADMIN"."WEATHER";
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."CITY" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEATHER
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."WEATHER" 
   (	"DATETIME" DATE, 
	"WIND_SPEED" NUMBER, 
	"WIND_DIRECTION" NUMBER, 
	"WIND_GUST" NUMBER, 
	"CITY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ADMIN.CITY
SET DEFINE OFF;
Insert into C##ADMIN.CITY (ID,NAME) values ('1','Izhevsk');
Insert into C##ADMIN.CITY (ID,NAME) values ('2','Samara');
Insert into C##ADMIN.CITY (ID,NAME) values ('3','Volgograd');
Insert into C##ADMIN.CITY (ID,NAME) values ('4','Saint-Petersburg');
REM INSERTING into C##ADMIN.WEATHER
SET DEFINE OFF;
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'3,8','84,2','10,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'22,4','220','30,6','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'3,4','72,3','10,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'13,6','239,8','36,5','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'24,6','240','35,6','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'20,1','250','35,8','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'20,1','260','35,8','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'17,9','260','36,7','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'22,4','260','33,6','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'16,6','262,2','41,6','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'26,8','260','38','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'29,1','260','42,5','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'29,1','260','42,9','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'29,1','270','40,3','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'26,8','260','43,6','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'17,2','261,7','43,2','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'24,6','260','38,5','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'22,4','280','35,3','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'22,4','270','33,3','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'22,4','280','28,4','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'15,7','280','27,3','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'9,4','275,5','23,3','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'11,2','270','21,3','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'2,7','78,7','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'3,4','75,5','11,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'5,1','77,8','14,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'5,1','76,3','15,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'5,6','77,3','18,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'4,9','82,7','17,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'4,9','88,7','11,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'5,8','89,7','12,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'4,9','92','8,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'4,9','85','8,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'5,4','85,4','7,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'5,1','86,8','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'5,1','91,4','6,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'4,7','96,2','6,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'3,8','89,4','5,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'2,9','92,7','5,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'0,7','175,3','0,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'1,8','219,9','1,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'2','234,1','2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'2','219','2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'2,2','216,1','2,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.04.22','DD.MM.RR'),'2,2','213,9','2,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('20.03.22','DD.MM.RR'),'11,6','291,6','26,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('17.03.22','DD.MM.RR'),'8,9','273,2','15,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('21.03.22','DD.MM.RR'),'13,4','338,6','29,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.03.22','DD.MM.RR'),'8,7','263,7','19,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.03.22','DD.MM.RR'),'5,4','207,1','11,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'5,8','222,1','21,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'4,9','215','19,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'4,7','208,3','17,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'4','192,9','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'4','184,8','10,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'4','176','9,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'4,3','174,1','15,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'5,4','177,9','23,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'7,6','182,4','23,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'8,9','182,4','25,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'9,2','176,1','26,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'9,4','174,9','26,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'10,1','174','26,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'10,3','169,2','26,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'11,2','168,2','28','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'11,2','172,5','28,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'11,4','170,4','26,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'12,1','172,6','28','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'13','174,6','31,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'11,9','174,4','29,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'11,6','172,2','28,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'12,3','177,6','29,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'12,1','174,8','29,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.04.22','DD.MM.RR'),'12,1','171,9','29,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'8,6','252','15,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,7','52,1','15,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'6,9','273,9','24,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'6,5','265,1','20,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'4,5','226','13,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'3,6','271','3,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'4,3','268,3','10,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'4,5','244','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'3,8','287,9','9,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'4','301,3','8,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'4,3','256','10,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'5,1','323,3','8,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'5,1','329,7','8,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'4,3','197','8,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'5,1','325,2','7,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'5,1','322,2','7,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'2,2','270','8,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'4,3','313,2','8,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'3,1','286,7','2,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'2,2','260','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'2,9','328,5','6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'2,5','358,4','5,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'2,2','200','4,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'2','330,7','2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'13,4','180,6','38,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'15,2','141','24,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'13','178,8','37,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'12,8','178,3','37,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'17,3','151','28,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'13,4','175,4','38,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'12,8','177','39,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'15,2','152','26,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'13','175,8','38,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'13','175,8','39,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'8,9','141','24,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'12,3','179,1','38,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'12,5','181,9','34,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'13,1','149','24,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'12,1','185,1','30,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'11,9','186','29,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'11,2','151','24,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'11,2','192,2','27,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'10,7','190,8','28','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'10,9','141','22,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'10,1','188,2','25,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'9,8','187,3','25,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'8,8','143','20','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('19.02.22','DD.MM.RR'),'9,4','190,4','25,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,5','188,4','35,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'8,8','160','17,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,1','190,2','36,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,1','187,9','34,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,7','160','17,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'9,8','183,2','33,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,3','183,1','34,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'8,6','141','17,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,5','179,7','35,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,7','179,7','38','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'8,8','121','20','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'11,9','178,9','37,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'12,3','179,3','36,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'10,9','151','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'12,5','179,5','36,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'12,8','177,7','36,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'17,3','152','26,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'13','177,2','36,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'12,5','175,8','36,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'19,5','143','30,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'13,9','178,2','38','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'13,4','182,5','37,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'8,9','160','24,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('18.02.22','DD.MM.RR'),'13,6','180,9','38,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'6,7','290,6','16,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'8,1','288','15,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'8,9','294,2','17,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'9,4','303,4','19,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'8,9','310','20,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'9,2','310,2','21,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'9,4','307,1','20,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'10,7','310,5','19,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'10,1','313,5','18,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'10,1','313,4','16,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'9,6','310,4','14,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'9,4','306,4','13,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'8,9','308,7','13','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'8,5','305,6','12,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'8,7','308,7','11,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'8,1','310,3','11','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'7,4','313,9','9,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'6,5','314','8,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'4,9','313,7','8,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'3,8','310,8','8,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'2,9','311,2','7,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'2','308,5','2,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'2,5','327,6','2,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.04.22','DD.MM.RR'),'2','328,3','2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'10,7','49,3','26,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'11,6','54,2','29,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'11,2','66,3','29,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'9,6','79','24,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'8,7','145,3','23,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'10,7','200,1','26,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'8,9','182,6','23','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'8,9','182,4','20,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'7,4','180,5','18,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'6,3','161,4','19,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'6,5','159,2','19','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'6,5','158','18,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'7,4','153,6','18,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'6,3','153','13,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'8,1','151,6','15,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'2,5','155,7','11,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'2','53,5','3,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'3,4','52,5','6,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'2,7','23','4,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'2,9','359,8','4,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'4','334,2','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'4,7','318,9','12,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'4,7','300,1','13,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.04.22','DD.MM.RR'),'6,7','306,2','17','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,1','170','8,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,9','81,8','2,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,9','67,7','4,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,2','75','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,9','64,3','6,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'3,1','61','8,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,5','77','11','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,5','88,9','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,7','90,1','7,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,5','61','11,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'5,1','88','7,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,7','81','6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'6,6','74','13,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,7','48,8','5,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,9','49,7','6,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,6','103','11,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'4,3','74,1','7,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'3,4','82,2','6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,4','74','7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,9','62,3','2,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'3,6','59,3','3,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'2,2','70','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.04.22','DD.MM.RR'),'3,8','55,2','11,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'3,6','173,5','8,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'2,1','180','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'3,1','144,9','7,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'3,4','157,9','6,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'2,2','103','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'4,7','161,8','11','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'4,3','137,1','11,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'4,5','103','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'5,4','132,6','14,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'5,6','133,6','16,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'4,3','93','11','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'6,5','132','19','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'6,7','122,4','20,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'6,6','114','11,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'6,5','126,1','19,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'6,5','121,2','20,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'4,6','139','9,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'5,6','123,1','19,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'5,4','114,5','19,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'6,7','93','9,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'4,9','108','16,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'5,1','103,7','15,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'4,3','63','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.04.22','DD.MM.RR'),'5,1','102','19','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'4,5','97','19,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'10,6','91','13,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'4','100,4','16,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'4,7','101,7','16,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'8,5','83','10,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'5,6','99,2','17,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'5,4','99,9','18,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'10,6','73','12,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'6,7','115,7','30','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'7,4','126,6','28,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'8,5','103','13,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'7,2','132,8','28,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'7,2','136','27,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'6,7','122','20','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'6,5','132,8','22,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'6,9','131,7','23,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'6,7','112','11,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'5,6','125','18,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'5,1','129,6','18,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'4,5','65','9,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'3,6','113,1','10,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'3,4','109,1','7,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'0,2','150','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.04.22','DD.MM.RR'),'3,1','104,5','7,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,5','88','4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,2','129','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,7','90,6','2,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,9','93,7','5,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'4,3','92','8,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,5','77,4','6,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,9','93,4','7,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'8,5','82','10,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,9','95,5','7,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,7','97,8','8,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'4,3','101','11','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'3,1','122,2','10,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'3,1','116,5','8,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'2,2','100','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'3,4','115,7','6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'3,4','108,6','6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'4,3','49','10,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'3,6','105,6','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'3,8','95,6','4,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'4,2','70','10,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'3,4','81,8','9,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'6,3','116','12,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'4,2','60','8,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.04.22','DD.MM.RR'),'1,8','47','1,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'2','63,2','1,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'6,4','83','13','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'2,5','87','2,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'3,4','101,5','3,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'8,5','73','13,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'5,6','92,5','14,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'5,1','88,6','15,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'6,4','81','13','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'5,4','87','15','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'5,6','92,4','13,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'4,3','64','11,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'7,4','99,4','14,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'7,4','98,2','13,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'4,6','72','15,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'7,6','104,9','13,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'7,4','109,7','13,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'4,5','46','13,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'5,1','115,5','16,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'3,1','109,8','6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'2,4','46','13,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'2,5','118,9','2,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'2,7','124,7','4,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'6,4','73','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.04.22','DD.MM.RR'),'2','77,6','3,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,2','184','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,7','241,6','2,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,7','228,8','2,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'4,2','180','8,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,2','184,5','2,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,7','172,9','2,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,2','161','6,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'3,4','200,5','8,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'4,3','213,7','9,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'4,3','225','10,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'4,7','240,6','9,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'5,1','255,5','9,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'0','255,5','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'5,6','254,9','8,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'6','253,1','8,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'4,3','176','13,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'5,6','233,7','9,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'5,4','229,2','11,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'4,2','190','13','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,7','217,6','2,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,2','221,5','2,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'2,2','140','6,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'0,4','272,7','0,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('24.03.22','DD.MM.RR'),'12,3','261,6','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('24.03.22','DD.MM.RR'),'8,9','243,8','17,2','2');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'11,9','220,8','29,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'8,6','191','19,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'10,7','224,4','24,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'10,7','228,6','22,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'9,8','226,9','20,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'8,9','228,5','19,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'7,8','224,5','19','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'6','238,8','16,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'5,8','233,5','14,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'4,7','236,1','12,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'3,6','232,7','6,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'3,1','238','4,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'3,1','278,7','5,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'1,6','1,3','1,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'2,9','63,6','2,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'3,6','109,3','6,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'5,4','83','11,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'6,5','75,8','16,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'7,6','68,5','20,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'7,6','66,7','22,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'7,4','63,1','21,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'6,9','91,2','20,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'11','178,8','25,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'11,4','182,1','24,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'13,4','200','24,8','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'17,9','220','26,8','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.04.22','DD.MM.RR'),'22,4','230','22,4','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'11,6','170,6','32,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'12,1','200,3','26,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'10,1','241,6','21,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'10,7','257,4','24,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'10,5','250,7','22,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'9,2','248,9','23,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'8,9','255,9','25,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'8,7','249,5','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'8,3','252,8','16,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'8,3','247,8','16,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'8,9','242,3','15,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'9,6','237,5','15,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'9,2','234','15','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'11','238,3','18,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'10,5','237,8','19,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'11,6','242,4','21,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'11,2','249,9','20,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'9,8','256,3','20,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'8,3','257,5','19,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'7,2','252,9','21','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'6,3','244,8','21,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'10,5','170,4','22,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'13','200,9','24,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'14,1','230,2','25,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11','256','21,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'8,5','247,3','18,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'9,2','269,2','20,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'10,1','277,9','21,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11','285,1','23,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11,9','291,8','21,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'12,3','292,8','21,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11,9','290,5','21','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11,9','288,5','20,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11,4','284,7','19,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11,6','283,7','20,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'11,2','283,1','19,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'10,7','279,9','19,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'9,6','276,4','19,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'8,3','271','18,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'7,4','257,9','16,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'6,9','245,2','16,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'6,5','237,4','19,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'6,7','230,1','23,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'6,7','226,9','23,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.04.22','DD.MM.RR'),'6,5','225,9','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'11,9','168,5','30,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'6','238,1','19,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.04.22','DD.MM.RR'),'5,1','235,2','17,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'1,8','214,9','1,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'0,7','189,2','0,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'1,1','5,6','1,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'2,2','34,7','2,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'2,9','96,6','2,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'2','63,1','2,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'2,9','32,5','6,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'2,9','59,6','7,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'3,8','72,7','8,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'4','58,8','8,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'4,7','56,5','9,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'5,4','56,2','9,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'5,6','38,9','11,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'5,6','41,2','14,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'6','37,8','13,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'6,5','30,9','16,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'7,6','51,4','13,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'6,9','37,8','16,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'6,7','37,8','18,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'6,9','20,2','21,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'7,4','30,8','23,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'7,6','26,5','24,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'9,4','36,3','27,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.04.22','DD.MM.RR'),'10,3','42,9','29,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('30.03.22','DD.MM.RR'),'10,7','239,1','27,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'6','218,1','10,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('31.03.22','DD.MM.RR'),'24,6','222,3','32,2','3');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('22.03.22','DD.MM.RR'),'12,3','278,8','25,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('23.03.22','DD.MM.RR'),'11','277,2','24,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('25.03.22','DD.MM.RR'),'12,8','179,6','27,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('26.03.22','DD.MM.RR'),'17,3','143,4','34','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('27.03.22','DD.MM.RR'),'19,5','175,7','36','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('28.03.22','DD.MM.RR'),'9,4','253,2','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('29.03.22','DD.MM.RR'),'15,3','163,9','25,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.03.22','DD.MM.RR'),'8,1','222,6','18,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.03.22','DD.MM.RR'),'8,6','191,3','13,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('04.03.22','DD.MM.RR'),'4,3','191,4','7,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('05.03.22','DD.MM.RR'),'19,5','92,9','37,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('06.03.22','DD.MM.RR'),'19,7','292,1','37,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('07.03.22','DD.MM.RR'),'4,9','296','9,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.03.22','DD.MM.RR'),'6,4','61,4','10,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('09.03.22','DD.MM.RR'),'8,9','129,1','23','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('10.03.22','DD.MM.RR'),'9,2','100,1','22,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('11.03.22','DD.MM.RR'),'8,1','47,8','19,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('12.03.22','DD.MM.RR'),'6,4','115,6','8,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('13.03.22','DD.MM.RR'),'8,9','227,4','20','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('14.03.22','DD.MM.RR'),'8,1','144,3','13,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('15.03.22','DD.MM.RR'),'11','90,3','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('16.03.22','DD.MM.RR'),'9,4','53,1','22,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('24.02.22','DD.MM.RR'),'8,8','247,7','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('25.02.22','DD.MM.RR'),'8,1','236','16,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('26.02.22','DD.MM.RR'),'10,3','178,9','21,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('27.02.22','DD.MM.RR'),'6,4','93,3','12,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('28.02.22','DD.MM.RR'),'7,6','156','20,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('01.03.22','DD.MM.RR'),'8,6','281,4','24,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('20.02.22','DD.MM.RR'),'13,3','177,6','32','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'6,7','99,6','17,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'6,9','91,6','16,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'6,7','94','15','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'8,9','99,2','19,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'8,7','111,6','24,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'8,5','102','21,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'8,1','108,2','21,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'9,8','149,2','34,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'10,1','160,2','34,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'11,6','162,7','38,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'11,9','165,7','37,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'12,5','173,4','39,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'12,5','186,8','39,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'12,1','188,7','36,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'12,1','188,2','35,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'12,3','195,1','34,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'13,4','196','37,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'13,4','194,2','38,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'14,3','199,5','36,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'14,3','205,1','35,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'15','218,3','37,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'13,2','218,8','38','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'11,9','220,9','35,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('03.04.22','DD.MM.RR'),'12,5','216,3','32,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'4,7','52,1','15,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'5,6','58,5','17','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'6','60','19,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'7,4','65','24,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'8,3','67,5','25,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'8,9','66,4','25,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'9,2','67','26,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'9,6','62,6','26,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'9,8','62,6','26,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'10,7','63,4','26,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'10,5','64,1','25,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'11','62,9','25,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'11,4','63,7','25,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'11,2','62,7','25,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'11','66,3','24,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'11,2','64,6','25,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'10,1','61,4','25,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'9,8','65,8','25,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'10,5','65,8','24,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'9,4','68,7','23,5','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'8,1','67,2','21,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'9,2','74,1','21,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'8,9','88,8','17,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('02.04.22','DD.MM.RR'),'6,3','96,4','17,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,7','231,7','15,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,3','223,6','13,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,3','207,7','12,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,5','197,7','11,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'3,4','162,3','7,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'5,4','147,9','12,3','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'6,3','139,7','15,4','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'7,8','139,2','19','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'8,3','135,9','20,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'8,9','143,7','22,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'8,5','135,9','21','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'7,4','145,3','20,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'7,4','134','16,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'6,3','143,4','14,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'5,4','158,3','16,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,7','161,9','16,8','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,7','195,7','12,1','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,3','181,9','11,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,5','182,6','10,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'5,1','210,2','10,7','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4,7','213,4','11,2','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'4','196,4','11,9','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'3,6','191,3','11,6','1');
Insert into C##ADMIN.WEATHER (DATETIME,WIND_SPEED,WIND_DIRECTION,WIND_GUST,CITY_ID) values (to_date('08.04.22','DD.MM.RR'),'2,9','192,8','7,6','1');
--------------------------------------------------------
--  DDL for Index CITY_NAME_UINDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_NAME_UINDEX" ON "C##ADMIN"."CITY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_PK" ON "C##ADMIN"."CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WEATHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."WEATHER_PK" ON "C##ADMIN"."WEATHER" ("DATETIME", "CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_PK" ON "C##ADMIN"."CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_NAME_UINDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CITY_NAME_UINDEX" ON "C##ADMIN"."CITY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WEATHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."WEATHER_PK" ON "C##ADMIN"."WEATHER" ("DATETIME", "CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ADMIN"."CITY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WEATHER
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."WEATHER" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."WEATHER" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."WEATHER" ADD CONSTRAINT "WEATHER_PK" PRIMARY KEY ("DATETIME", "CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEATHER
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."WEATHER" ADD CONSTRAINT "CITY_ID" FOREIGN KEY ("CITY_ID")
	  REFERENCES "C##ADMIN"."CITY" ("ID") ENABLE;
